/*
    Definicoes Internas da WebBrowse
*/

#DEFINE BR_TITULO	01			// Titulo da Columa
#DEFINE BR_CAMPO    02          // Nome do Campo / Expresao
#DEFINE BR_TIPO		03			// Tipo do Campo (C/N/D/L)
#DEFINE BR_TAMANHO  04          // Tamanho do Conteudo do Campo
#DEFINE BR_DECIMAL  05          // Numero de Casas Decimais
#DEFINE BR_PICTURE  06          // Picture de Visualizacao Advpl
#DEFINE BR_WIDTH	07			// Tamanho da Coluna em PIXELS

